### ISSUE TITLE
Can have output in PyCharm?

### ISSUE THREAD

**Issue by Uzver123** [overfl0/IDAPython-pycharm-setup#3]
Is there way to get ida output inside Pycharm console to don''t switch to ida after running python code?

**Comment by overfl0** [comment]
Hi, thanks for the report.

I was usually opening a separate terminal and running
```
python -m jupyter_console --existing --ZMQTerminalInteractiveShell.include_other_output=true
```
on a different monitor so that it doesn't waste my screen space, so I never really noticed that this was an issue.

To get the output, you should open `pycharm_wrapper.py` and replace every `execute()` with `execute_interactive()` and remove the `reply=True` argument. I haven't tested it extensively so I'm not committing it to the repository yet, just in case.

**Comment by overfl0** [comment]
Okay, should be fixed and working in the latest `master`

**Comment by Uzver123** [comment]
Nice thank you in the past script errors were not showing in IDA console or PyCharm so had to run script from IDA execute script Shift+2 to troubleshoot,  if any errors it prints in PyCharm console and not in IDA which is good.

**Comment by Uzver123** [comment]
When using print() is there way to make output go only to pycharm console? Right now its duplicated in both Pycharm and IdaPro
