### ISSUE TITLE
PyCharm script error format is messy

### ISSUE THREAD

**Issue by Uzver123** [overfl0/IDAPython-pycharm-setup#4]
Hi if i run script in IDA execute script Shift+F2:

```
import ida_kernwin

input_str = ida_kernwin.ask_str('', 0, 'enter text')

input_arr = input_str.split(':')

```

Then instead of providing value click **Cancel** button in user input dialog, ida console output looks like this:

```
Script import ida_kernwin

input_str = ida_kernwin.ask_str('', 0, 'enter text')

input_arr = input_str.split(':')
 error: Traceback (most recent call last):
  File "<string>", line 5, in <module>
AttributeError: 'NoneType' object has no attribute 'split'

```

If i run same script in PyCharm and press **Cancel** button then error printed in PyCharm console looks like this, not easy to see what's going on.

```
culling sys module...
←[1;31m---------------------------------------------------------------------------←[0m
←[1;31mAttributeError←[0m                            Traceback (most recent call last)
File ←[1;32mD:\Settings and Profiles\PyCharm\Projects\IDA Pro\temp.py:5←[0m
←[0;32m      1←[0m ←[38;5;28;01mimport←[39;00m ←[38;5;21;01mida_kernwin←[39;00m
←[0;32m      3←[0m input_str ←[38;5;241m=←[39m ida_kernwin←[38;5;241m.←[39mask_str(←[38;5;124m'←[39m←[38;5;124m'←[39m, ←[38;5;241m0←[39m, ←[38;5;124m'←[39m←[38;5;124menter text←[39m←
[38;5;124m'←[39m)
←[1;32m----> 5←[0m input_arr ←[38;5;241m=←[39m ←[43minput_str←[49m←[38;5;241;43m.←[39;49m←[43msplit←[49m(←[38;5;124m'←[39m←[38;5;124m:←[39m←[38;5;124m'←[39m)

←[1;31mAttributeError←[0m: 'NoneType' object has no attribute 'split'

```

**Comment by overfl0** [comment]
This is caused by the "Emulate terminal in output console" checkbox in the configuration settings (see first screenshot in Readme).
Unchecking it makes these characters work as color codes.

At this moment, I have completely no idea why I suggested to check that box, but it surely had a purpose, back in the day.
You're welcome to try unchecking it and reporting back if you stumble upon any issues with it.
Maybe things that were causing issues 2 years ago are now gone and that setting is not needed anymore 🤷‍♂️

**Comment by Uzver123** [comment]
Fixed thanks.
